dist: xenial
services:
  - docker

language: python
cache:
  pip: true
  directories:
    - .mypy_cache

os:
  - linux
install:
  - pip install tox-travis
jobs:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"

script: tox
branches:
  only:
    - master
notifications:
  email: false
